{% set name = "perl-fastx-abi" %}
{% set version = "0.10" %}
{% set sha256 = "7f9c825cee7031ee85c32b07514a0ff1a8d821bd390385e1fa036d629bb01456" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PR/PROCH/FASTX-Abi-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-test-warnings >=0.005
    - perl-cpan-meta-check
    - perl-cpan-meta-requirements
    - perl-extutils-makemaker
    - perl-bio-trace-abif

  run:
    - perl
    - perl-carp
    - perl-bio-trace-abif

test:
  imports:
    - FASTX::Abi

about:
  home: https://github.com/telatin/FASTX-Abi
  license: MIT
  summary: 'FASTX::Abi - Read Sanger trace file (.ab1 chromatograms) in FASTQ format. For traces called with hetero option, the ambiguities will be split into two sequences to allow usage from NGS tools that usually do not understand IUPAC ambiguities. '
  doc_url: https://metacpan.org/pod/FASTX::Abi
  description: |
    This module reads a Sanger trace (chromatogram). If the chromatogram was saved in "hetero" mode, that is allowing IUPAC
    ambiguities in the basecalling, the module will return two (unphased) sequences in standard "ACGT" alphabet.
